set nocompatible

filetype off

" General settings
set backspace=indent,eol,start  " Defines what backspace does in insert mode
set ruler        " Show the line and column number in the status line
set number       " show line number
set showcmd
set showmatch    " Highlight matching parenthesis
set incsearch    " Show the matching tokens when search a pattern
set hlsearch     " Highligh a previous search if any
set scrolloff=20 " Let some space around the cursor to see the context
set tabstop=4    " Number of spaces for a Tab
set shiftwidth=4 " Size of the autoindent

syntax on

" Mappings ---------------------------------------------------------------- {{{
" The leader globally used
let mapleader = ","

" Easily set the working directory to the file
" currently edited
map <leader>cd :cd %:p:h<cr>:pwd<cr>

" Explores the buffer
map <leader>o :BufExplorer<cr>

" Save the current buffer
map <leader>w :w!<cr>

" Window Navigation
"Move to the window below  
nnoremap <C-J> <C-W><C-J>
"Move to the window above
nnoremap <C-K> <C-W><C-K>
"Move to the window on the right
nnoremap <C-L> <C-W><C-L>
"Move to the window on the left
nnoremap <C-H> <C-W><C-H> 

" vimrc ------------------------------------------------------------------- {{{
" Sourcing vimrc
nnoremap <leader>sv :source $MYVIMRC<CR>


" Help navigation --------------------------------------------------------- {{{
" jump to links with CR
autocmd FileType help nmap <buffer> <CR> <C-]>
" jump back with BS
autocmd FileType help nmap <buffer> <BS> <C-T>
" skip to next option link
autocmd FileType help nmap <buffer> o /'[a-z]\{2,\}'<CR>:nohls<CR>
" skip to previous option link
autocmd FileType help nmap <buffer> O ?'[a-z]\{2,\}'<CR>:nohls<CR>
" skip to next subject link
autocmd FileType help nmap <buffer> s /\|\S\+\|<CR>l:noh<CR>:nohls<CR>
" skip to previous subject link
autocmd FileType help nmap <buffer> S h?\|\S\+\|<CR>l:noh<CR>:nohls<CR>
" quit
autocmd FileType help nmap <buffer> q :q<CR>
